name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Publish new package')
   

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        docker login --username KuryGabriele --password ${{ secrets.GH_PAT }} ghcr.io
        docker buildx use $(docker buildx create --platform linux/amd64,linux/arm64 --name mybuilder)
        docker buildx build --platform=linux/amd64,linux/arm64 . --tag ghcr.io/echo-project-org/echo-server:latest
        docker push ghcr.io/echo-project-org/echo-server:latest
    
