name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Publish new package')
    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/echo-project-org/echo-server:latest
          platforms: linux/amd64,linux/arm64
          no-cache: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=registry,dest=ghcr.io/echo-project-org/echo-server:latest

      # - name: Build the Docker image
      #   run: |
      #     docker login --username KuryGabriele --password ${{ secrets.GH_PAT }} ghcr.io
      #     docker buildx use $(docker buildx create --platform linux/amd64,linux/arm64 --name mybuilder)
      #     docker buildx build --platform=linux/amd64,linux/arm64 --output=type=registry,dest=ghcr.io/echo-project-org/echo-server:latest --tag ghcr.io/echo-project-org/echo-server:latest . 