name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Publish new package')
   

    steps:
    - uses: actions/checkout@v3
    - name: Install python3 pip
      run: sudo apt install python3 python3-pip
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag echo-server:$(date +%s)
    
